# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqiRQDwBFaIVkCIRqfNBh8QjE9du_MER
"""

!pip install flask flask-cors pyngrok scikit-learn pandas numpy requests

import pandas as pd
import numpy as np


np.random.seed(42)

# Phishing URLs (label = 1)
phishing_urls = [
    "http://paypa1-secure-login.xyz/verify/account",
    "http://192.168.1.1/bank/login.php",
    "http://secure-update-amazon.tk/signin",
    "http://appleid-verify.ml/update",
    "http://fblogin-secure.ga/checkpoint",
    "http://www.paypal-update-info.com/login",
    "http://secure.bankofamerica-update.com/verify",
    "http://netflix-billing-update.xyz/account",
    "http://instagram-verify-account.ml/login",
    "http://amazon-security-alert.tk/signin",
]

# Safe URLs (label = 0)
safe_urls = [
    "https://www.google.com/search?q=python",
    "https://github.com/topics/machine-learning",
    "https://stackoverflow.com/questions/tagged/python",
    "https://www.amazon.com/products/electronics",
    "https://www.youtube.com/watch?v=abc123",
    "https://www.facebook.com/profile",
    "https://www.linkedin.com/in/username",
    "https://docs.python.org/3/library",
    "https://www.wikipedia.org/wiki/Python",
    "https://www.netflix.com/browse",
]

# Combine చేయి
all_urls = phishing_urls + safe_urls
labels = [1]*10 + [0]*10

df_sample = pd.DataFrame({'url': all_urls, 'label': labels})
print("✅ Sample dataset created!")
print(df_sample)

import requests
import io

# UCI ML Phishing Dataset - FREE & RELIABLE
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00327/Training%20Dataset.arff"

try:
    print("📥 Downloading real dataset...")


    print("✅ Using generated realistic dataset (500 samples)")

    def generate_dataset(n_samples=500):
        data = []


        phishing_patterns = [
            "http://secure-{brand}-login.xyz/{action}",
            "http://{ip}/bank/login.php",
            "http://{brand}-verify-{word}.tk/{action}",
            "http://www.{brand}-update-info.ml/login",
        ]

        brands = ['paypal', 'amazon', 'netflix', 'apple', 'facebook', 'google']
        actions = ['verify', 'update', 'signin', 'login', 'account', 'secure']
        words = ['alert', 'security', 'billing', 'confirm', 'validate']
        ips = ['192.168.1.1', '10.0.0.1', '172.16.0.1']

        safe_domains = [
            'google.com', 'amazon.com', 'facebook.com',
            'github.com', 'youtube.com', 'linkedin.com',
            'stackoverflow.com', 'wikipedia.org'
        ]

        # Generate phishing
        for i in range(n_samples // 2):
            brand = np.random.choice(brands)
            action = np.random.choice(actions)
            word = np.random.choice(words)
            ip = np.random.choice(ips)

            url_type = np.random.randint(0, 4)
            if url_type == 0:
                url = f"http://secure-{brand}-login.xyz/{action}"
            elif url_type == 1:
                url = f"http://{ip}/bank/login.php?user=admin"
            elif url_type == 2:
                url = f"http://{brand}-{word}.tk/{action}/confirm"
            else:
                url = f"http://www.{brand}-update-{word}.ml/login"

            data.append({'url': url, 'label': 1})

        # Generate safe
        for i in range(n_samples // 2):
            domain = np.random.choice(safe_domains)
            paths = ['search', 'products', 'profile', 'home', 'about']
            path = np.random.choice(paths)
            url = f"https://www.{domain}/{path}"
            data.append({'url': url, 'label': 0})

        return pd.DataFrame(data)

    df = generate_dataset(500)
    print(f"✅ Dataset ready! Shape: {df.shape}")
    print(df['label'].value_counts())
    print(df.head())

except Exception as e:
    print(f"Error: {e}")
    df = df_sample

import re
from urllib.parse import urlparse

def extract_features(url):
    features = {}

    try:
        parsed = urlparse(url)
        domain = parsed.netloc
        path = parsed.path

        # ── 1. LENGTH FEATURES ──
        features['url_length'] = len(url)
        features['domain_length'] = len(domain)
        features['path_length'] = len(path)

        # ── 2. SPECIAL CHARACTER FEATURES ──
        features['has_at_symbol'] = 1 if '@' in url else 0
        features['has_double_slash'] = 1 if '//' in url[7:] else 0
        features['has_dash_in_domain'] = 1 if '-' in domain else 0
        features['dot_count'] = url.count('.')
        features['slash_count'] = url.count('/')
        features['question_count'] = url.count('?')
        features['equals_count'] = url.count('=')
        features['underscore_count'] = url.count('_')

        # ── 3. SECURITY FEATURES ──
        features['has_https'] = 1 if url.startswith('https') else 0
        features['has_http'] = 1 if url.startswith('http://') else 0

        # ── 4. IP ADDRESS CHECK ──
        ip_pattern = r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
        features['has_ip_address'] = 1 if re.search(ip_pattern, url) else 0

        # ── 5. SUSPICIOUS WORDS ──
        suspicious_words = [
            'login', 'verify', 'secure', 'update', 'bank',
            'account', 'confirm', 'signin', 'validate', 'alert',
            'billing', 'password', 'credential', 'access'
        ]
        features['suspicious_word_count'] = sum(
            1 for word in suspicious_words if word in url.lower()
        )

        # ── 6. BRAND NAMES (possible spoofing) ──
        brands = ['paypal', 'amazon', 'netflix', 'apple',
                 'facebook', 'google', 'microsoft', 'instagram']
        features['has_brand_name'] = sum(
            1 for brand in brands if brand in url.lower()
        )

        # ── 7. SUSPICIOUS TLD (Top Level Domain) ──
        suspicious_tlds = ['.xyz', '.tk', '.ml', '.ga', '.cf', '.gq']
        features['suspicious_tld'] = 1 if any(
            url.lower().endswith(tld) or tld + '/' in url.lower()
            for tld in suspicious_tlds
        ) else 0

        # ── 8. URL DEPTH ──
        features['url_depth'] = len([x for x in path.split('/') if x])

        # ── 9. DIGIT COUNT ──
        features['digit_count'] = sum(c.isdigit() for c in url)

        # ── 10. SHORTENING SERVICES ──
        shorteners = ['bit.ly', 'tinyurl', 'goo.gl', 't.co', 'short.link']
        features['is_shortened'] = 1 if any(
            s in url for s in shorteners
        ) else 0

    except:
        # If URL parsing fails, fill zeros
        for key in features:
            if key not in features:
                features[key] = 0

    return features

# ── TEST பண்ணு ──
test_url = "http://paypa1-secure-login.xyz/verify/account"
features = extract_features(test_url)

print("🔍 Features for:", test_url)
print("-" * 50)
for key, value in features.items():
    print(f"  {key:30s} → {value}")

from sklearn.preprocessing import StandardScaler

print("⚙️ Extracting features for all URLs...")


feature_list = []
for url in df['url']:
    features = extract_features(url)
    feature_list.append(features)


X = pd.DataFrame(feature_list)
y = df['label']


X = X.fillna(0)

print(f"✅ Feature matrix shape: {X.shape}")
print(f"✅ Features: {list(X.columns)}")
print(f"\n📊 Label distribution:")
print(f"   Safe URLs (0): {sum(y==0)}")
print(f"   Phishing URLs (1): {sum(y==1)}")

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import (accuracy_score, classification_report,
                              confusion_matrix)
import matplotlib.pyplot as plt
import seaborn as sns

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Training samples: {len(X_train)}")
print(f"Testing samples:  {len(X_test)}")

models = {
    'Random Forest': RandomForestClassifier(
        n_estimators=100, random_state=42
    ),
    'Gradient Boosting': GradientBoostingClassifier(
        n_estimators=100, random_state=42
    ),
    'Logistic Regression': LogisticRegression(
        max_iter=1000, random_state=42
    )
}

print("\n📊 Model Comparison:")
print("=" * 45)

results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)
    results[name] = acc
    print(f"  {name:25s} → {acc*100:.2f}%")

best_model_name = max(results, key=results.get)
best_model = models[best_model_name]
print(f"\n🏆 Best Model: {best_model_name} ({results[best_model_name]*100:.2f}%)")

# ── Best model predictions ──
y_pred = best_model.predict(X_test)

print("📋 Classification Report:")
print(classification_report(y_test, y_pred,
      target_names=['Safe', 'Phishing']))

# ── Confusion Matrix ──
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Safe', 'Phishing'],
            yticklabels=['Safe', 'Phishing'],
            ax=axes[0])
axes[0].set_title('Confusion Matrix', fontsize=14)
axes[0].set_ylabel('Actual')
axes[0].set_xlabel('Predicted')

# Plot 2: Feature Importance
if hasattr(best_model, 'feature_importances_'):
    importances = best_model.feature_importances_
    feat_df = pd.DataFrame({
        'feature': X.columns,
        'importance': importances
    }).sort_values('importance', ascending=True).tail(10)

    feat_df.plot(kind='barh', x='feature', y='importance',
                ax=axes[1], color='steelblue', legend=False)
    axes[1].set_title('Top 10 Important Features', fontsize=14)
    axes[1].set_xlabel('Importance Score')

plt.tight_layout()
plt.savefig('phishing_results.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graph saved!")

import pickle
with open('phishing_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)


feature_names = list(X.columns)
with open('feature_names.pkl', 'wb') as f:
    pickle.dump(feature_names, f)

print("✅ Model saved as 'phishing_model.pkl'")
print(f"✅ Features saved: {len(feature_names)} features")

def predict_url(url, model=best_model):

    features = extract_features(url)
    feature_values = [features.get(col, 0) for col in X.columns]


    prediction = model.predict([feature_values])[0]
    probability = model.predict_proba([feature_values])[0]

    confidence = max(probability) * 100
    result = "🚨 PHISHING" if prediction == 1 else "✅ SAFE"

    print(f"\n{'='*55}")
    print(f"  URL: {url[:50]}...")
    print(f"  Result: {result}")
    print(f"  Confidence: {confidence:.1f}%")
    print(f"{'='*55}")


    if hasattr(model, 'feature_importances_'):
        top_features = sorted(
            zip(X.columns, feature_values, model.feature_importances_),
            key=lambda x: x[2], reverse=True
        )[:5]

        print("  📌 Top Reasons:")
        for feat, val, imp in top_features:
            print(f"     • {feat}: {val}")

    return prediction, confidence

test_urls = [
    "http://paypal-secure-update.xyz/verify/account",
    "https://www.google.com/search?q=python",
    "http://192.168.1.1/banking/login.php",
    "https://github.com/scikit-learn/scikit-learn",
    "http://amazon-security-alert.tk/signin/confirm",
]

print("🔍 Testing URLs...")
for url in test_urls:
    predict_url(url)

import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# UI Elements
url_input = widgets.Text(
    placeholder='Enter URL to check...',
    description='URL:',
    layout=widgets.Layout(width='500px')
)

check_btn = widgets.Button(
    description='🔍 Check URL',
    button_style='primary',
    layout=widgets.Layout(width='150px')
)

output = widgets.Output()

def on_check(b):
    with output:
        clear_output()
        url = url_input.value.strip()

        if not url:
            print("⚠️ Please enter a URL!")
            return

        if not url.startswith('http'):
            url = 'http://' + url

        pred, conf = predict_url(url)

        if pred == 1:
            display(HTML(f"""
            <div style='background:#ffe0e0; padding:15px;
                        border-radius:10px; border:2px solid red'>
                <h2 style='color:red'>🚨 PHISHING DETECTED!</h2>
                <p><b>URL:</b> {url}</p>
                <p><b>Confidence:</b> {conf:.1f}%</p>
                <p>⚠️ Do NOT visit this website!</p>
            </div>
            """))
        else:
            display(HTML(f"""
            <div style='background:#e0ffe0; padding:15px;
                        border-radius:10px; border:2px solid green'>
                <h2 style='color:green'>✅ SAFE URL</h2>
                <p><b>URL:</b> {url}</p>
                <p><b>Confidence:</b> {conf:.1f}%</p>
                <p>This URL appears to be legitimate.</p>
            </div>
            """))

check_btn.on_click(on_check)

display(HTML("<h2>🛡️ Phishing URL Detector</h2>"))
display(widgets.HBox([url_input, check_btn]))
display(output)